### ISSUE TITLE
Event 2: Ascending The Peak

### ISSUE THREAD

**Issue by roniRamon** [roniRamon/big-project#10]
this event is not clear and i don't understand it, not from the tec' spec and not from the story
can someone please make it clear.
for example you come across 3 option with the fairy but non of them are explained
and then it moves on to go left(will be elaborated ??)
and go right

**Comment by cNikhil** [comment]
Hey srry, I'll update it tmrw to match the tech spec and make some changes

**Comment by goshasawicka** [comment]
Waiting for the logic of the story before I can do anything in the Tech Spec. (if no story corrections will appear till Sun,11.22, evening will rewrite the story keeping as much original plot as possible)

**Comment by goshasawicka** [comment]
story has been rewritten in the Tech Spec
