### ISSUE TITLE
Can start game even if a stat less is than 10

### ISSUE THREAD

**Issue by Lutalo** [roniRamon/big-project#14]
**Expected result:** Not being able to start game if a stat is less than 10
**To reproduce:** Allocate less than 10 points to a stat, and begin your adventure

**Comment by FominOlga** [comment]
It's not yet clear in FS if the minimum amount of points should be 10 or 1. Waiting for the details.

**Comment by jbpascual** [comment]
The minimum will be 1. However, the game can still start while stats are at 0.

**Comment by tjdunlap** [comment]
At the current standing, the FS remarks the minimum amount is 1 to each attribute. As of the current game, a character with 0-0-0 attributes may begin gameplay.

**Comment by goshasawicka** [comment]
If somebody wants to make their game more difficult they can set less than points. System will not allow negative which is fine and monimum is 0 and not 1, so it also work. This is mentioned in the Tech Spec which I'm currently reviewing, so closing this issue.
