### ISSUE TITLE
Stat and Money fields can be user edited

### ISSUE THREAD

**Issue by Lutalo** [roniRamon/big-project#15]
Editing the money field allows you to change the amount of money your character has. 
**To reproduce:** Replace the number in the money field with any number greater than 1300. Buy a sword from the first merchant you encounter. Buy the second sword from the second merchant you encounter. The second purchase is allowed even your character legitimately does not have the money.

**Comment by roniRamon** [comment]
fixed - disabled money, health, strength, smart
