### ISSUE TITLE
Image+text about yourself: for each group member

### ISSUE THREAD

**Issue by FominOlga** [roniRamon/big-project#18]
Please send your picture (150x150 px or I can resize it myself) and 2 sentences about yourself to ofomin@mail.ccsf.edu. This is for 'About' page.

**Comment by jbpascual** [comment]
What should the text contain, random personal trivia or, say, our role in the project?

**Comment by FominOlga** [comment]
Each role in a project will be indicated by default. Sentences:

My example: 'Olga is a promising front-end web developer with the philological background. She enjoys: a good book, a cup of tea and when this goddamn piece of code is finally working!'

Gosha's example: "I'm nutrition and sudoku lover who have been trying to make it out for living (nutrition didn't work so far). Pain in the ... stomach for any inconsistency in the project documentation. "

I'd prefer to have all sentences written in the format 'PersonsName is... bla-bla. He/She...bla-bla'

**Comment by rowvln** [comment]
The About Page looks good. We are just waiting for one more person it seems.
