### ISSUE TITLE
Money goes to negative - see tech spec for prevention

### ISSUE THREAD

**Issue by goshasawicka** [roniRamon/big-project#19]
In Tech Spec I have added revised logic to prevent money to go negative

forest river: 
- pay to pass by boat. if player doesnt have enough money to pay for the ride, they will give whatever they have and money will be 0
- play dice with monster: if you loose and do not have enough money to pay 10$, play till you win (or die out of loosing health).

I forest hole : money is multiplied by 0.5 (so loosing always half and rounding to integer)

forest dead body: money is set to 0.

Other stories have only adding money or in case of purchases (merchant stories) have already implemented validation.

**Comment by roniRamon** [comment]
closed: change story river to  if player doesnt have enough money to pay for the ride, they will give whatever they have and money will be 0
and demon story if no money go back the long way

**Comment by roniRamon** [comment]
closed: change story river to if player doesnt have enough money to pay for the ride, they will give whatever they have and money will be 0
and demon story if no money go back the long way
