### ISSUE TITLE
Testing schedule

### ISSUE THREAD

**Issue by goshasawicka** [roniRamon/big-project#20]
Tests will be available to perform after Monday 29th Nov. 
Please do not test yet until we have confirmation from Roni and Olga that scripts are complete (estimate given above).

In the documentation I have added "..Test template" file with a structured way to and explain steps taken and where the problem occurs. 

Please refer to it at tests to make it easier later to reproduce errors.

**Comment by FominOlga** [comment]
Yes I think Monday is a realistic date. I still need to change this and that though.
