### ISSUE TITLE
About page - no pictures and hard to read

### ISSUE THREAD

**Issue by goshasawicka** [roniRamon/big-project#24]
The About page is not readable - all profiles are overlapping and it's hard to read.
Plus it does not show pictures yet.

**Comment by FominOlga** [comment]
Fixed overlapping in Chrome browser.
Waiting for images from other group members.

**Comment by FominOlga** [comment]
Still waiting for a photo+text from Steven and Rowvin!!

**Comment by FominOlga** [comment]
Steven, you are the last with text!!! Took  your photo from github.

**Comment by rowvln** [comment]
Olga, the picture you took from Github was mine, not Steven.

**Comment by rowvln** [comment]
This is Steven's github. https://github.com/Lutalo

**Comment by FominOlga** [comment]
You're right, sorry! I don't know why I decided to put two of your pics, I might just like you too much :)

**Comment by rowvln** [comment]
Haha no problem. :p

**Comment by FominOlga** [comment]
Closing this one as duplicate to #18
