### ISSUE TITLE
Containers for penguins are removed but needed for tutorial purpose

### ISSUE THREAD

**Issue by FominOlga** [roniRamon/big-project#25]
Please remove:
        $('#penguin1').hide();
    $('#penguin2').hide();
    $('#penguin3').hide(); 

And add 
$('#penguin1').css('background-image', 'url("images/penguin.png")');
$('#penguin2').css('background-image', 'url("images/penguin.png")');
$('#penguin3').css('background-image', 'url("images/penguin.png")');

when a penguin is collected. Otherwise container for penguins is hidden completely.

**Comment by roniRamon** [comment]
The penguin is hidden until you finish a level once you complete a level penguin is visible!!! If you need them for the tutorial create a new one and then delete him !!! I'm no changing the code for the tutorial
