### ISSUE TITLE
Content of 'Hints'

### ISSUE THREAD

**Issue by FominOlga** [roniRamon/big-project#27]
Please check and update wording for 'Hints' and specify if we need to add different content for each area/page. If yes, please provide the appropriate content.

**Comment by Lutalo** [comment]
Most of the content in the Hints page is now irrelevant to the game.
It probably needs a rewrite.

**Comment by jbpascual** [comment]
I will rewrite it, but I'd like for us to get the game balancing done first.

**Comment by tjdunlap** [comment]
Note: Made mention of this and suggestions of possible ways to re-write in Issue #48

**Comment by FominOlga** [comment]
Any updates on 'Hints'? I suggest we leave it as it is?

**Comment by Lutalo** [comment]
My suggestion is to remove the first hint: "Having trouble finding out where to go? Talk to the townsfolk!"
as it doesn't really apply much anymore.

I also suggest to add a last motivational hint in: "Keep trying! Not everybody succeeds their first time. Every death leads you closer to victory."

**Comment by FominOlga** [comment]
Updated.
