### ISSUE TITLE
inconsistency with pop ups in desert stories

### ISSUE THREAD

**Issue by yochess** [roniRamon/big-project#30]
There are some inconsistencies with the pop ups when an item is obtained. Not sure if you guys want to fix it.

There is no pop up for obtaining items from the following stories:

A. Desert - Merchant: KNIFE, SWORD, APPLE
     1. attack him
     2. next (spelling bug: text box displays some code)
         (pop up: i win)
     3. take knife, sword, and apple
     4. next (spelling bug: when you open backpack, sowrd is misspelled).

B. Desert - Merchant: APPLE, possibly SWORD too
    1. try to buy something
    2. buy apple

Then the following do have pop ups:

A. Desert - Cactus Island: CACTUS
    1. continue walking
    2. walk towards cactus island
    3. get cactus
        (pop up: obtained cactus)

B. Desert - Cactus Island: CACTUS
    1. dig
    2. continue walking
    3. walk to cactus island
    4. get cactus
        (pop up: obtained cactus)

C. Desert - Canyon: NEEDLE
     1. make noise
     2. fight troll
     3. get needle: y/n?
          a. yes
              (pop up: got needle)
          b. no
              (pop up: no needle) // this isn't necessary

**Comment by roniRamon** [comment]
if you guys want to add alerts please tell me and i will add....

**Comment by yochess** [comment]
I think it would be a good idea to add an alert to the users that they've obtained an item. I have to check my backpack everytime I buy/get something.

Most of the stories don't alert.

**Comment by roniRamon** [comment]
add alert to every place where you get an item
