### ISSUE TITLE
home page: can play with over 100 points

### ISSUE THREAD

**Issue by yochess** [roniRamon/big-project#31]
If I distribute my stats accordingly, the begin adventure box replaces the welcome box.
Then when I distribute my stats over 100:

eg)
health: 1000
strength: 1000
intelligence: 1000
, 
I am still able to begin the game.

**Comment by roniRamon** [comment]
fix points !!! see if works good

**Comment by yochess** [comment]
Yes it works now. The stats won't update unless it adds upto 100
