### ISSUE TITLE
Mountain - Merchant

### ISSUE THREAD

**Issue by yochess** [roniRamon/big-project#33]
Going into the mountain - merchant story with these items:
Lollipop, 
Mountain lion tooth

If I attack the merchant and win in the mountains section,

the story tells me I obtain these items:
small knife,
large sword, 
whiskey (whisky is misspelled)

a) The next button will not work. 
b) I also don't seem to have a choice. I have to obtain these items. (the desert merchant on the other hand gave me a choice).

**Comment by roniRamon** [comment]
the next button works, i don't see how it does not work for you....???? can you try again
before you do pull the new changes...
and i will give a player an option to take or not take stuff..

**Comment by roniRamon** [comment]
gave the option to take items or not ... if yes take all items if not keep going...

**Comment by yochess** [comment]
yes both options works. I may have had too many items.
