### ISSUE TITLE
Mountain Event 1

### ISSUE THREAD

**Issue by cNikhil** [roniRamon/big-project#35]
Mountain Event 1
# Game> You round a narrow corner on the mountain ledge. Your gaze meets the eyes of a mountain lion

choice 2. run away
# Game> 1. Run ahead.
# Game> You run towards the cat. Startled, it turns around and books it.

This isn't a bug, but the logic seems very flawed. Clicking "run away" results in you running toward
the cat.

**Comment by jbpascual** [comment]
It's intentional, you get the option of running forwards or backwards. I apologize the logic isn't as sound as the rest of the game is.
