### ISSUE TITLE
Mountain Event 2

### ISSUE THREAD

**Issue by cNikhil** [roniRamon/big-project#36]
Mountain Event 1
# Game> You round a narrow corner on the mountain ledge.

choice 3. Show you're not a threat.

Mountain Event 2
# Game>You enter the Mountains. The penguin could be anywhere

choice 1. Fight her for the sword

If you fight her for the sword and win, no other choices are presented.

**Comment by roniRamon** [comment]
Make sure you pull the new files before you play ...
It works for me so try to pull and check again
