### ISSUE TITLE
New stories to be added in FS

### ISSUE THREAD

**Issue by goshasawicka** [roniRamon/big-project#4]
Hey,
There has been new stories in the Stories folder. I have added 2 merchant stories in Mountains and Desert and there was another one in Mountains (in total 3 new ones) that has to be added in the Functional Spec.

I will adjust Tech Spec with it.

**Comment by goshasawicka** [comment]
One more story is in Desert Part. Story 5 - Pyramid (There was no name of it so I have called it whatever, author can change it as they wish)

**Comment by jbpascual** [comment]
Thanks. I've added them to the flowchart.
