### ISSUE TITLE
Intelligence isn't needed for extra options

### ISSUE THREAD

**Issue by jbpascual** [roniRamon/big-project#41]
Even with 0 Intelligence the extra options in certain events are displayed and can be chosen. For example, option 3 in Mountain 1 and option 2 in Desert 1.

**Comment by Lutalo** [comment]
I also had this bug.

**Comment by roniRamon** [comment]
we change the technical spec to fix the issue

**Comment by goshasawicka** [comment]
The scope has been changed, so that is now a feature. Tech spec has been adjusted to accommodate this logic.
