### ISSUE TITLE
Money isn't reset after death

### ISSUE THREAD

**Issue by jbpascual** [roniRamon/big-project#42]
When you die and start a new game your Money will remain at what it last was.

**Comment by roniRamon** [comment]
i tested it and i don't see it, the money is starting at 500 again can you try it again and put the steps the you took...

**Comment by Lutalo** [comment]
I got this issue too.
Played the game through, won, and then pressed quit.
At the character creation screen, I refreshed the browser page.
All the input fields were pre-filled in. I didn't change any fields and pressed Begin Adventure.
The money did not reset.

**Comment by roniRamon** [comment]
can you try again i fix the quit button but I'm not sure about the other

**Comment by tjdunlap** [comment]
FYI: Money is still not resetting by death or quitting.

**Comment by roniRamon** [comment]
money is resetting if you do quit

**Comment by roniRamon** [comment]
please try again all browser and in chrome try in this link http://hills.ccsf.edu/~rramon3/gamePrototype/index.html#home-page
try quit and to die and see if it reload

**Comment by tjdunlap** [comment]
It works in both scenarios. :)

**Comment by tjdunlap** [comment]
Note: In Firefox, the Quit button and Victory Screen Restart button will not clear the cash. Death will.

**Comment by roniRamon** [comment]
is it just the quit and reset in the victory screen ?

**Comment by roniRamon** [comment]
can you test it now in firefox? with the new version??

**Comment by roniRamon** [comment]
Can someone please check if it works on Firefox ???

**Comment by yochess** [comment]
I just died while on firefox with $0

$$ is back to 500 afterwards.

**Comment by roniRamon** [comment]
Thank you so It's good for all browsers:)
We can close this issue ...
