### ISSUE TITLE
Forest: can pay to cross river when you have no money

### ISSUE THREAD

**Issue by cNikhil** [roniRamon/big-project#44]
Forest:
1. you are crossing the meadow
        -walk away
2. you meet a merchant
       -buy sword
3. you want to enter the dark forest
       -you go in without any light
4. you fall in hole
       -start crying
5. you reach crossroad
       -take shortcut
6. fight demon and lose
7. you have to cross the river
      -pay $15 dollars

You can pay to get across even though you don't have any money. Also, I fought demon 6 times with a 0 strength character and won 4 times.

**Comment by cNikhil** [comment]
Ignore the last part about demon, I forgot I had the sword. Also, when you buy the sword and come across another sword later on the dead body, you can't take it. WHY CAN'T I HAVE TWO SWORDS.

**Comment by roniRamon** [comment]
we talk about that and that what we said.. if you take sword you can't take other sword...

**Comment by cNikhil** [comment]
Haha ok I was kidding anyways.
