### ISSUE TITLE
Forest: missing choice button

### ISSUE THREAD

**Issue by cNikhil** [roniRamon/big-project#45]
Forest:
1. you are crossing the meadow
-walk away
2. you meet a merchant
-buy sword
3. you want to enter the dark forest
-you go in without any light
4. you fall in hole
-start crying
5. you reach crossroad
-take shortcut
6. fight demon and lose
7. you have to cross the river
-pay $15 dollars
8. you come across a body
-examine it

When choosing to take the apple, the "no" button is not present. Instead, It's the code for the button: 
input type="button" value="No" id="noApple" data-inline="true" data-mini="true" data-icon="check" class="noApple">

**Comment by roniRamon** [comment]
are you sure you are playing in the right version?? because i check it and i don't see it??

**Comment by cNikhil** [comment]
I just pulled about 30 minutes ago.

**Comment by roniRamon** [comment]
apple fixed 
please make sure to put all your steps so i can know what you are  talking about
