### ISSUE TITLE
FS outline & Game inconsistencies

### ISSUE THREAD

**Issue by tjdunlap** [roniRamon/big-project#48]
Found a few inconsistencies. If someone wants to tackle and make them reflect the FS, do let me know? Otherwise, I will edit the FS to reflect the current In-Game action.

*First off, I just want to confirm is this statement is correct or not: (Overview) The Tale of Tux is... played in a browser on both desktop and mobile devices.

*Functional Specification Statement:  (Character Creation: Enter a Name) A maximum of 16 characters can be inputted in the field.
In Game: This cap does not exist.

*Functional Specification Statement: (Character Creation: Attribute Distribution) Each attribute begins at a value of 1 that cannot be made lower
In Game: All attributes default to 0. In fact, the game can be initialized with 0 in all three fields.

*Functional Specification Statement: (Character Creation: Attribute Distribution) A “Reset” button sets the value of each attribute back to 1.
In Game: All attributes reset to 0.

*Functional Specification Statement: (Main Game) There is a header at the top of the page that shows the game’s logo on the left.
In Game: I'm not seeing this once we pass Begin Adventure.

*Just something I noticed...: Hints.
In Game: I see the text, but really.. I feel there is no manner in which 2 of these will help inspire thought. I think hint no.2 and hint no.3 could remain as is, but no.1 is pointless as there are no events within the HubCity. Perhaps we could mention that once an item is placed within your backpack, your character will not discard it? no.4 could be changed to mention not having enough money as intelligence doesn't play a role in merchant events.

*Noticed: (Forest Story) Go in without any light.
In Game: If you select Go in without any light., the following will then be displayed:
Go in without any light.
You enter the forest without any light. You cannot see anything, its all dark around you. You make a few steps and you fall into a deep hole in the ground. What do you do?
Note: Just seems a bit redundant. I'm sure it'd be dandy leaving it as is, though.

*Functional Specification Statement: (Game Over Screen) Shows the words “Game Over” in magnificent fashion. Underneath, a “Restart” button brings the player back to the Title Screen.
In Game: A pop-up dialogue appears reading, "You are dead!!! Start over" The button below reads "Ok"

*Functional Specification Statement: (Victory Screen) Shows the words “You Win!” in marvelous fashion. Underneath, a “Restart” button brings the player back to the Title Screen.
In Game: The text box reads "Congrats!! You won the fight with the Brick and you have managed to Save Prince. Well Done!!! The End." There is no button to restart.

**Comment by FominOlga** [comment]
Mobile devices: not in this version :(
 A maximum of 16 characters: will be limited to 16, there is an opened issue for that I'm working on.
All attributes default to 0: see issue #14, so we agreed that 0 is fine.
 All attributes reset to 0: so that should is correct
Game’s logo: will be visible only on home and about pages.
Hints should be more specific and helpful or removed.
Game Over: we've decided with Roni that alert and redirection to the home page is ok.
For 'You win' there will be a separate page with text and restart button (working on it)

**Comment by tjdunlap** [comment]
Thanks Olga! I'll update the FS shortly. Good luck!
