### ISSUE TITLE
'You win!' image

### ISSUE THREAD

**Issue by FominOlga** [roniRamon/big-project#49]
Update 'You win!' image and make a transparent background for it.

**Comment by roniRamon** [comment]
were is it and should i redirect the end to it instead of the win massage ?

**Comment by FominOlga** [comment]
The victory page is there please redirect there when player wins.

**Comment by roniRamon** [comment]
fixed redirect to victory page

**Comment by jbpascual** [comment]
Fixed in f6ffb5f62523f13e6b1e223673938077e4e1c646
