### ISSUE TITLE
change alerts for your dead

### ISSUE THREAD

**Issue by roniRamon** [roniRamon/big-project#52]
please play the game and try to die!!!
i what to check the new alert for Game over 
post your issues!!!! thank you

**Comment by tjdunlap** [comment]
Black message box appears. Text in white:  You are dead!!!! Game over
Located below to the left is a button reading "Start over" Game restarts with blank fields.

**Comment by roniRamon** [comment]
Good :)

**Comment by roniRamon** [comment]
w if everybody saw this we can close it ...
