### ISSUE TITLE
Stuck: Entering the Python's Nest with no penguins

### ISSUE THREAD

**Issue by tjdunlap** [roniRamon/big-project#53]
Entered the Python's Nest with no Penguins immediately at the beginning of the game. Neither option will do anything, but the circles upon each will change to blue, and both stay as such. Perhaps an Exit button to return to the crossroad should be implemented?

!!!Edit!!!
Entered the forest after the tutorial. Option selection works up to selecting the area. After such, no option selection is making any progression. Unlike the Python Nest, the highlighted circle in the forest will jump from whichever I choose to the next I choose. Going to try and few more areas and another browser after this. Currently playing in Firefox.

**Comment by roniRamon** [comment]
you are not working on the right version of the game !!!!!

**Comment by tjdunlap** [comment]
Oh snap. My bad.

Edit: Unless the Syncing is a lie, or we're booting from a new file, I'm still experiencing this issue in Firefox.

**Comment by roniRamon** [comment]
Still no working?

**Comment by tjdunlap** [comment]
Yeah. :/

**Comment by rowvln** [comment]
I second this issue. I pulled the latest version and wasnt able to continue on the python screen.

**Comment by tjdunlap** [comment]
Newest update fixed this. Thanks! :)
