### ISSUE TITLE
Game initialized, all penguins in inventory

### ISSUE THREAD

**Issue by tjdunlap** [roniRamon/big-project#54]
Or at least, they are all on display

**Comment by roniRamon** [comment]
try pulling the new version of the game

**Comment by tjdunlap** [comment]
Yeah sorry. I thought I did but I must not have. My apologies.

Edit: I am up to date. Working in firefox. Unless we're running it from a new file, I'm still seeing them. (opening from gamePrototype/index)

**Comment by roniRamon** [comment]
try now (pull new version ) should work

**Comment by tjdunlap** [comment]
Looks good!
