### ISSUE TITLE
Dead Body Story: Text issue?

### ISSUE THREAD

**Issue by tjdunlap** [roniRamon/big-project#59]
If you come across the second the body with an empty backpack and select to run, the following text appears: You have run away in panic and lost one of your artifacts from your backpack undefined

**Comment by roniRamon** [comment]
did you have any items in backpack before ?

**Comment by roniRamon** [comment]
fixed so if no artifacts  don't show it ...
many i should write: "You have run away in panic and lost one of your artifacts from your backpack(if you have any )"??

**Comment by tjdunlap** [comment]
Well, if you have an item, it will state what was lost in place of undefined. In the previous body instance, there's a similar text that does not react to an empty backpack when you run, so maybe just remove whatever is stating what was lost?

**Comment by roniRamon** [comment]
Ok fixed :)
