### ISSUE TITLE
Starting game with Attributes undefined

### ISSUE THREAD

**Issue by tjdunlap** [roniRamon/big-project#60]
Rather than read 0 in the Health Box in game, it reads disabled.

Edit: Actually, my bad. Deleted 0 and did not enter a value of 0 in its place.
If you play through with this, gaining health will then change it to read NaN.
Attempted to fight the demon to see what would happen if health is lost...

**Comment by roniRamon** [comment]
If you start with 0 ?

**Comment by tjdunlap** [comment]
If you start with 0, it's fine.

**Comment by tjdunlap** [comment]
If you loose health while NaN is on the box, all options will disappear and there will be no progression.

**Comment by roniRamon** [comment]
So I don't understand when this happens???

**Comment by tjdunlap** [comment]
Basically, changed my mind during character creation, deleted the value but did not enter a 0. want screen shots? :)

**Comment by tjdunlap** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/15132395/11759213/2f366d16-a02b-11e5-9895-5991a5581c77.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/15132395/11759216/2f3c68c4-a02b-11e5-8f0e-d81af120371d.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/15132395/11759215/2f38b09e-a02b-11e5-8890-ee0e23ab5986.jpg)
![untitled-4](https://cloud.githubusercontent.com/assets/15132395/11759214/2f387660-a02b-11e5-8a23-9fd1f9d64912.jpg)

**Comment by tjdunlap** [comment]
Same thing happens with Strength it seems. If there's a next button that initiates a fight roll, you get stuck there, but can click next for different fight roll results.
![untitled-1](https://cloud.githubusercontent.com/assets/15132395/11759258/e7b34760-a02b-11e5-8509-96e84bbe46b9.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/15132395/11759259/e7b72eca-a02b-11e5-8b3f-ba3a466b2649.jpg)

**Comment by tjdunlap** [comment]
If intelligence is disabled, options pertaining to intelligence will appear.
![untitled-1](https://cloud.githubusercontent.com/assets/15132395/11759321/21a02690-a02d-11e5-9bcf-293a4915f2a8.jpg)

**Comment by roniRamon** [comment]
fixed attr to star from 1 if you put nothing...

**Comment by tjdunlap** [comment]
...Is that merchant option a random event? Attempted to replicate, and no Start Conversation option. Wanted to test intelligence options with disabled ><
![untitled-1](https://cloud.githubusercontent.com/assets/15132395/11759390/3462c566-a02e-11e5-87fc-ea06f1d337aa.jpg)
