### ISSUE TITLE
Intelligence options don't appear..?!

### ISSUE THREAD

**Issue by tjdunlap** [roniRamon/big-project#61]
Wanted to see if there was a difference in dialogue for another test and guess what I found?
![untitled-1](https://cloud.githubusercontent.com/assets/15132395/11759336/65113b76-a02d-11e5-8124-2e505a36c2fd.jpg)

Guess the character is too smart for their own good. xP

q: is that a random event? thought it was an int-rated one ><

**Comment by roniRamon** [comment]
fixed
