### ISSUE TITLE
Testing doc review

### ISSUE THREAD

**Issue by goshasawicka** [roniRamon/big-project#62]
Few comments:

point 2 in the testing flow is not required (tester IS a team member). If someone reported a bug coder never waited for confirmation from anyone else (ask Roni if you have doubt).

Document structure: missing "... results of multiple rounds of user testing ..." which should be an essential part of the doc.
If you want to add our process it's fine as the intro, but MAIN part are testing results which should be main focus and explicitly extracted to a separate section.

We can have following sections from this doc:
-Testing process (report bug, fix it retest it. if problem still unsolved needed another round of fix - retest) - whose can be points as it so intuitive what that means
-Types of errors and problems we faced during testing:
1. Bugs (very broad category and can be divided)
1.1 Players atributes parameters not validated in events (intelligence in #61, money #50 )
1.2 Random logic (#34)
1.3 buttons not working (#33)
1.4 Backpack ($47)
1.5 Visibility of the code on the screen and (#36)
1.6 Wording and spelling in the games' UI
2. Inconsistency of the game
3. Inconsistency of documentation documentation (written by diff ppl i various formats)
4. Undesired activity (any other idea for the name, because looking at it, it's hard to understand what it refers to. Maybe Script Security?)
5. Design issues.
6. Problem with current version. (Some bugs were fixed but testers didn't pull the latest version, so problem was solved before reporting it 

I encourage anyone else to put their comments as to what the document should contain, as we were all in the classroom when Brick was explaining it.

**Comment by yochess** [comment]
Here's the latest one. Seriously, feel free to make edits to this doc guys. I'm pretty sure my grammar isn't the best and I may have left out a thing here and there.

https://docs.google.com/document/d/1DynU5TlZcZOJbsyYA1u6VgWUlQTS6xoibgsJObGb49Q/edit
