### ISSUE TITLE
Too much death?

### ISSUE THREAD

**Issue by jbpascual** [roniRamon/big-project#7]
Does anyone think there are too many paths that lead to death in the stories? Might be a good idea to change them to -Health instead so players don't get too frustrated.

**Comment by goshasawicka** [comment]
That is very generic statement. Please try to be more specific (like which stories are too cruel). 

I think only desert stories are more harsh. If you think it's getting too cruel, please contact the author of the story and discuss. Everyone was contributing and have influence on the plot, so it's up to individual story creators to decide how they want to set the logic.

This will be taken offline (face to face) individual cases assigned to authors.

**Comment by yochess** [comment]
That may be really just my stories. I'll change it to health instead.
