### ISSUE TITLE
Mountain Story 2 mislabeled

### ISSUE THREAD

**Issue by jbpascual** [roniRamon/big-project#8]
This event involves getting the Penguin for the Mountain, so it should changed to Event P3 (see FuncSpec_flowchart.png). Since @cNikhil wrote it, could you also update it so the text fits the flow better? Thanks.

**Comment by goshasawicka** [comment]
Event has been adjusted in the Tech Spec. It does not include getting the penguin which is out of any individual story. Penguins are collected instead at the end of each location as an additional page or a popup message.
